# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Executable

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Init Environment
      run: chmod +x ./scripts/build/common.sh && ./scripts/build/common.sh

    - name: Build for Linux
      run: chmod +x ./scripts/build/linux.sh && ./scripts/build/linux.sh

    - name: Build for windows
      run: chmod +x ./scripts/build/windows.sh && ./scripts/build/windows.sh

    - name: Build for Android
      run: chmod +x ./scripts/build/android.sh && ./scripts/build/android.sh

#    - name: Upload Linux artifact
#      uses: actions/upload-artifact@v4
#      with:
#        name: linux-amd64
#        path: fyne-cross/dist/linux-amd64/omamori

    - name: Upload release binary
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG_NAME="${GITHUB_REF#refs/tags/}"
        gh release create "$TAG_NAME" omamori \
          --title "Release $TAG_NAME" \
          --notes "Automated release for $TAG_NAME"

