# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Executable

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'
    
    - name: Install X11 development libraries
      run: sudo apt-get update && sudo apt-get install -y gcc libgl1-mesa-dev libxcursor-dev libxkbcommon-dev libx11-dev
    
    - name: Install dependencies
      run: go mod download
    
    - name: Build
      run:  go build -v -o omamori ./app

    - name: Upload release binary
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG_NAME="${GITHUB_REF#refs/tags/}"
        gh release create "$TAG_NAME" omamori \
          --title "Release $TAG_NAME" \
          --notes "Automated release for $TAG_NAME"
